version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/kevgo/tikibase
    steps:
      - checkout
      - run: GO111MODULE=on go test ./...
      - run: GO111MODULE=on go get github.com/cucumber/godog/cmd/godog
      - run: .circleci/run-godog.sh
