version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/kevgo/tikibase
    steps:
      - checkout
      - run: make unit
      - run: go get github.com/cucumber/godog/cmd/godog
      - run: rm -rf vendor
      - run: godog --format=progress
